spring:
  application:
    name: Eureka
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: true
    peer-node-read-timeout-ms: 1000
#  instance:
#    hostname: localhost
